### ISSUE TITLE
Proxy for all requests

### ISSUE THREAD

**Issue by bhaktadas** [jzz4012650/simple_proxy#8]
Hi!

Now I  try to use your extension (thank you for it!) and filled in the Proxy and Host fields (in the White sheet) - for example website.com.

Does this mean that only requests to the host website.com + his js, css etc. located on the same hosting will go directly, and all requests to its CDN, counters etc. (which are located on other hosts but open in THIS tab) will go through a proxy?

In other words, does your extension only apply to the hosts I have specified, or to all requests that this host creates in this tab?

Thank you beforehand.

**Comment by jzz4012650** [comment]
- White List Mode: Only hosts in White list will not go through proxy server, all other hosts not in white list will go through proxy server;
- Black List Mode: Only hosts in Black list will go through proxy server, all other hosts not in black list will not go through proxy server;

**Comment by bhaktadas** [comment]
I get it, thanks.
